---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netperfserver-pvc
  namespace: kbench-pod-namespace
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netperfclient-pvc
  namespace: kbench-pod-namespace
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
