---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netperfserver-pvc
  namespace: kbench-pod-namespace
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Storage class deployed in Constellation
  # remove storage class for GCP/AKS
  storageClassName: encrypted-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netperfclient-pvc
  namespace: kbench-pod-namespace
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Storage class deployed in Constellation
  # remove storage class for GCP/AKS
  storageClassName: encrypted-storage
