apiVersion: v1
kind: Pod
metadata:
  name: mynetperfclientpod
  namespace: kbench-pod-namespace
  labels:
    name: mynetperf
    podtype: client
spec:
  volumes:
  - name: netperfclient-volume
    persistentVolumeClaim:
      claimName: netperfclient-pvc
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: podtype
            operator: In
            values:
            - server
        topologyKey: kubernetes.io/hostname
  hostname: netperfclient
  subdomain: kbench-service-oid-0-tid-0
  containers:
  - image: gcr.io/google-containers/nginx
    resources:
      limits:
        memory: "2400Mi"
      requests:
        memory: "2400Mi"
        ephemeral-storage: "5Gi"
    volumeMounts:
    - name: netperfclient-volume
      mountPath: /tmp/perfoutput
    command: ["/bin/sh","-c"]
    args:
      - wget https://github.com/HewlettPackard/netperf/archive/netperf-2.7.0.tar.gz;
        tar xf netperf-2.7.0.tar.gz && cd netperf-netperf-2.7.0;
        ./configure && make && make install;
        sleep infinity;
    name: netperfclientcontainer
