apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-block-pvc
  namespace: kbench-pod-namespace
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Storage class deployed in Constellation
  # remove storage class for GKE/AKS
  storageClassName: encrypted-storage
